#!/usr/bin/env python3
"""
provenance_audit.py -- can this repository say who wrote its verification code?

Measures the Provenance Reconstruction Rate (PRR): the fraction of eligible
units whose authorship class can be established from post-hoc repository
records under a FROZEN evidence hierarchy.

    PRR = reconstructible units / eligible units

The hierarchy is frozen here, in code, before any unit is scored:

    Tier 1  contemporaneous generation record (agent/API/tool log)   ADMISSIBLE
    Tier 2  contemporaneous explicit attribution (file header, PR)   ADMISSIBLE
    Tier 3  commit message naming a model                            ADMISSIBLE
    Tier 4  retrospective human declaration          SENSITIVITY ANALYSIS ONLY
    Tier 5  inferred from coding style / fingerprint        INADMISSIBLE

Tier 5 is inadmissible by construction -- this tool cannot express it. Allowing
"this looks like it was written by X" would make the experiment circular: the
outcome would be inferred from the same text the outcome is measured on.

Tiers 1 and 2 are not discoverable from git alone; this tool reports them as
structurally absent unless a sidecar manifest supplies them. That absence is a
result, not a gap in the tool.

ARTIFACT CLASSES are separated because the estate that motivated this tool
credits AI contribution in prose while recording nothing for code:

    verification  a .py file containing a pass/fail, accept/reject, or
                  healthy/unhealthy decision reaching an exit code
    code          any other .py file
    prose         .md and other text

Reporting one pooled PRR across all three would hide exactly the asymmetry
worth measuring.

Run:  python3 provenance_audit.py <repo> [<repo> ...]
      python3 provenance_audit.py --selftest

Exit: 0 if the audit completes (whatever the PRR turns out to be), or if the
      selftest passes. 1 if the selftest fails or no eligible unit is found.
      A LOW PRR IS A RESULT, NOT A BUILD FAILURE -- this tool must not exit
      nonzero merely because provenance is poor, or nobody could run it on a
      repository with poor provenance, which is the case it exists to measure.
"""

import argparse
import ast
import json
import os
import re
import subprocess
import sys
import tempfile

# ---------------------------------------------------------------- frozen sets
# Frozen before any unit was scored. Adding a name here after seeing results
# would be fitting the instrument to the data.
MODELS = [
    "claude", "chatgpt", "gpt-4", "gpt-5", "gpt-o", "openai",
    "kimi", "copilot", "deepseek", "grok", "perplexity", "gemini", "llama",
]
MODEL_RE = re.compile("|".join(MODELS), re.IGNORECASE)

# A commit message must name a model AND assert authorship, not merely mention
# one. "fix per Claude's review" is Tier 3; "compare against Claude output" is
# a topic reference and does not establish who wrote the code.
AUTHORSHIP_RE = re.compile(
    r"(co-?authored-?by|generated by|written by|authored by|"
    r"drafted by|per|via|with|using|from)\s*:?\s*[^\n]{0,40}(" +
    "|".join(MODELS) + ")",
    re.IGNORECASE,
)

HEADER_RE = re.compile(
    r"^\s*(#|\*\*|//)?\s*(author|co-?author|contributor|credit)s?\b",
    re.IGNORECASE,
)

# Verdict-carrying constructs. A file is verification-shaped if it can reach a
# nonzero exit -- i.e. it is able to say no.
VERDICT_CALLS = {"exit"}


def git(repo, *args):
    try:
        p = subprocess.run(["git", "-C", repo, *args],
                           capture_output=True, text=True, timeout=120,
                           errors="replace")
        return p.stdout if p.returncode == 0 else ""
    except Exception:
        return ""


def is_verification_shaped(path):
    """True if the file can reach a nonzero exit: it is able to refuse."""
    try:
        src = open(path, errors="replace").read()
        tree = ast.parse(src)
    except Exception:
        return False
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            fn = node.func
            name = getattr(fn, "attr", None) or getattr(fn, "id", None)
            if name in VERDICT_CALLS and node.args:
                a = node.args[0]
                # sys.exit(1) / sys.exit(0 if ok else 1) / sys.exit(rc)
                if isinstance(a, ast.Constant) and a.value not in (0, None):
                    return True
                if isinstance(a, (ast.IfExp, ast.Name, ast.Call, ast.BinOp)):
                    return True
        if isinstance(node, ast.Raise):
            return True
    return False


def classify_artifact(rel):
    if rel.endswith(".md") or rel.endswith(".txt"):
        return "prose"
    if rel.endswith(".py"):
        return "code"
    return "other"


def header_attribution(path):
    """Tier 2: contemporaneous explicit attribution inside the file itself."""
    try:
        with open(path, errors="replace") as f:
            head = [next(f, "") for _ in range(40)]
    except Exception:
        return None
    for line in head:
        if HEADER_RE.match(line) and MODEL_RE.search(line):
            return line.strip()[:120]
    return None


def audit(repo):
    name = os.path.basename(os.path.abspath(repo.rstrip("/")))
    log = git(repo, "log", "--format=%H%x1f%s%x1f%b%x1e")
    commits = {}
    for rec in log.split("\x1e"):
        rec = rec.strip("\n")
        if not rec:
            continue
        parts = rec.split("\x1f")
        if len(parts) < 3:
            continue
        sha, subj, body = parts[0], parts[1], parts[2]
        commits[sha] = subj + "\n" + body

    # Tier 3: which commits assert model authorship?
    tier3 = {s for s, m in commits.items() if AUTHORSHIP_RE.search(m)}
    mentions = {s for s, m in commits.items() if MODEL_RE.search(m)}

    files = [f for f in git(repo, "ls-files").splitlines() if f.strip()]
    units = []
    for rel in files:
        cls = classify_artifact(rel)
        if cls == "other":
            continue
        full = os.path.join(repo, rel)
        if not os.path.exists(full):
            continue
        if cls == "code" and is_verification_shaped(full):
            cls = "verification"

        # Tier 2
        t2 = header_attribution(full)
        # Tier 3: did any authorship-asserting commit touch this file?
        touching = set(git(repo, "log", "--format=%H", "--", rel).split())
        t3 = bool(touching & tier3)

        if t2:
            tier, reconstructible = 2, True
        elif t3:
            tier, reconstructible = 3, True
        else:
            tier, reconstructible = None, False

        units.append({"repo": name, "path": rel, "class": cls,
                      "tier": tier, "reconstructible": reconstructible})

    return {
        "repo": name,
        "commits": len(commits),
        "commits_mentioning_model": len(mentions),
        "commits_asserting_authorship": len(tier3),
        "units": units,
    }


def summarize(results):
    rows = [u for r in results for u in r["units"]]
    out = {"by_class": {}, "by_repo": {}, "totals": {}}
    for cls in ("verification", "code", "prose"):
        sub = [u for u in rows if u["class"] == cls]
        n = len(sub)
        rec = sum(1 for u in sub if u["reconstructible"])
        out["by_class"][cls] = {
            "eligible": n, "reconstructible": rec,
            "PRR": round(rec / n, 4) if n else None,
        }
    for r in results:
        sub = [u for u in r["units"] if u["class"] == "verification"]
        n = len(sub)
        rec = sum(1 for u in sub if u["reconstructible"])
        out["by_repo"][r["repo"]] = {
            "commits": r["commits"],
            "commits_mentioning_model": r["commits_mentioning_model"],
            "commits_asserting_authorship": r["commits_asserting_authorship"],
            "verification_units": n,
            "reconstructible": rec,
            "PRR": round(rec / n, 4) if n else None,
        }
    n = len(rows)
    rec = sum(1 for u in rows if u["reconstructible"])
    out["totals"] = {"eligible": n, "reconstructible": rec,
                     "PRR": round(rec / n, 4) if n else None}
    return out


def report(results):
    s = summarize(results)
    print("=" * 72)
    print("PROVENANCE RECONSTRUCTION RATE")
    print("Tiers 1-3 admissible. Tier 4 sensitivity only. Tier 5 inadmissible.")
    print("=" * 72)
    print("\nBy artifact class:")
    print(f"  {'class':<14}{'eligible':>10}{'recon':>8}{'PRR':>10}")
    for cls, d in s["by_class"].items():
        prr = "n/a" if d["PRR"] is None else f"{d['PRR']*100:.1f}%"
        print(f"  {cls:<14}{d['eligible']:>10}{d['reconstructible']:>8}{prr:>10}")

    print("\nVerification units by repository:")
    print(f"  {'repo':<32}{'commits':>8}{'assert':>8}{'units':>7}{'PRR':>9}")
    for repo, d in s["by_repo"].items():
        prr = "n/a" if d["PRR"] is None else f"{d['PRR']*100:.1f}%"
        print(f"  {repo:<32}{d['commits']:>8}"
              f"{d['commits_asserting_authorship']:>8}"
              f"{d['verification_units']:>7}{prr:>9}")

    v = s["by_class"]["verification"]
    p = s["by_class"]["prose"]
    print("\n" + "-" * 72)
    if v["PRR"] is not None and p["PRR"] is not None:
        print(f"ASYMMETRY: prose PRR {p['PRR']*100:.1f}%  vs  "
              f"verification PRR {v['PRR']*100:.1f}%")
        print("A gap here means the estate records which model contributed")
        print("which IDEA, and not which model wrote which GATE.")
    print("\nTier 1 (generation logs) and most Tier 2 evidence are not")
    print("recoverable from git. Their absence is a property of the")
    print("development workflow, not a limitation of this tool.")
    print("-" * 72)
    return s


# ------------------------------------------------------------------ selftest
POSITIVE = '''\
# Author: Chad Holland, with Claude (Anthropic)
import sys
if len(sys.argv) > 99:
    sys.exit(1)
sys.exit(0)
'''

NEGATIVE = '''\
import sys
print("no verdict here, and no attribution")
sys.exit(0)
'''

FINGERPRINT_BAIT = '''\
# This code has the unmistakable style of an AI assistant.
# Certainly! Here is a comprehensive solution.
import sys
if False:
    sys.exit(1)
sys.exit(0)
'''


def selftest():
    print("=" * 72)
    print("ANTI-VACUITY SELFTEST")
    print("=" * 72)
    ok = True
    with tempfile.TemporaryDirectory(
            dir=os.environ.get("TMPDIR") or os.path.expanduser("~")) as d:
        repo = os.path.join(d, "fixture")
        os.makedirs(repo)
        subprocess.run(["git", "init", "-q", repo], check=True)
        subprocess.run(["git", "-C", repo, "config", "user.email", "t@t"], check=True)
        subprocess.run(["git", "-C", repo, "config", "user.name", "t"], check=True)
        for fn, src in (("attributed.py", POSITIVE),
                        ("plain.py", NEGATIVE),
                        ("bait.py", FINGERPRINT_BAIT)):
            open(os.path.join(repo, fn), "w").write(src)
        subprocess.run(["git", "-C", repo, "add", "-A"], check=True)
        subprocess.run(["git", "-C", repo, "commit", "-q", "-m",
                        "add fixtures"], check=True)

        res = audit(repo)
        by = {u["path"]: u for u in res["units"]}

        # A: header attribution is found, and the unit is verification-shaped
        a = by.get("attributed.py", {})
        pa = a.get("reconstructible") is True and a.get("class") == "verification"
        print(f"\n  A attributed.py -> reconstructible verification unit: "
              f"{'PASS' if pa else 'FAIL'} "
              f"(tier={a.get('tier')}, class={a.get('class')})")
        ok = ok and pa

        # B: the instrument must be able to return NOT-reconstructible
        b = by.get("plain.py", {})
        pb = b.get("reconstructible") is False
        print(f"  B plain.py -> NOT reconstructible (instrument can say no): "
              f"{'PASS' if pb else 'FAIL'} (tier={b.get('tier')})")
        ok = ok and pb

        # C: Tier 5 is inadmissible -- style must never establish authorship
        c = by.get("bait.py", {})
        pc = c.get("reconstructible") is False
        print(f"  C bait.py -> style does NOT establish authorship "
              f"(Tier 5 inadmissible): {'PASS' if pc else 'FAIL'} "
              f"(tier={c.get('tier')})")
        ok = ok and pc

        # D: prose and verification are counted separately
        s = summarize([res])
        pd_ = s["by_class"]["verification"]["eligible"] >= 1
        print(f"  D verification units counted separately from prose: "
              f"{'PASS' if pd_ else 'FAIL'}")
        ok = ok and pd_

    print("\n" + "=" * 72)
    if ok:
        print("SELFTEST PASS -- this tool reports reconstructible AND")
        print("not-reconstructible depending on input, and refuses to infer")
        print("authorship from coding style. It is not stuck on one verdict.")
    else:
        print("SELFTEST FAIL -- do not trust output from this tool until fixed.")
    print("=" * 72)
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("repos", nargs="*")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--json", help="write the full unit table here")
    a = ap.parse_args()

    if a.selftest:
        return selftest()
    if not a.repos:
        ap.print_help()
        return 1

    results = [audit(r) for r in a.repos]
    s = report(results)
    if a.json:
        with open(a.json, "w") as f:
            json.dump({"summary": s,
                       "units": [u for r in results for u in r["units"]]},
                      f, indent=2)
        print(f"\nfull unit table -> {a.json}")
    if s["totals"]["eligible"] == 0:
        print("\nNo eligible units found. Exit 1.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
